apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.ollama.port }}
      targetPort: {{ .Values.ollama.port }}
      protocol: TCP
