{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kometa.fullname" . }}-config
  labels:
    {{- include "kometa.labels" . | nindent 4 }}
data:
  config.yml: |
{{ .Values.config | indent 4 }}
{{- end }}
