{{- if .Values.movieConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kometa.fullname" . }}-movies
  labels:
    {{- include "kometa.labels" . | nindent 4 }}
data:
  movies.yaml: |
{{ .Values.movieConfig | indent 4 }}
{{- end }}
