apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: app-unpoller
  labels:
    app: unpoller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpoller
  template:
    metadata:
      labels:
        app: unpoller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9130"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: unpoller
          image: docker.io/golift/unifi-poller:v2.11.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9130
              protocol: TCP
          env:
            - name: UP_UNIFI_DEFAULT_URL
              value: "https://10.0.1.254"
            - name: UP_UNIFI_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: unpoller-credentials
                  key: username
            - name: UP_UNIFI_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: unpoller-credentials
                  key: password
            - name: UP_UNIFI_DEFAULT_VERIFY_SSL
              value: "false"
            - name: UP_UNIFI_DEFAULT_SAVE_DPI
              value: "true"
            - name: UP_INFLUXDB_DISABLE
              value: "true"
            - name: UP_PROMETHEUS_DISABLE
              value: "false"
            - name: UP_PROMETHEUS_HTTP_LISTEN
              value: "0.0.0.0:9130"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
