---
# SealedSecret for Anthropic API key used by the terminal sidecar
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: esphome-terminal-anthropic-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgBfnRInXvrdU9eAJX4GbRHbQcP47CPHxbJwsxLESVXerG8zCsy75fug/9oTKmi2etxNfrN77vMvPKzjzbnh0Nmk4pltmyXsPXXtKywXgWZAs/sl6KeNwm39IDX9yK6oSO6OVNZf8EIcIv67rgco4QhfM/8G5D5jlPC7zX+SbI+KLC6t3sqkiEsZYXwEKlH6XpjZCw9SS2GaqjwY/uIYilfrYGq4c9hydGrh1M0B4CSzACZYRNWWF97UW7lONRcbyk6LAPDe8u1TsVXtsL4FGNLk/qVvlHKLPKBjDLGhY/IYLm6W8N4cHZ8HtRNXROZmK+lFUMHZLNsomFQ7Rzxkn69GGOZvYTDkn9TgyOeJDnvjkXrGgpMJOUfiYc9nxm38jJp4afG7hlq/xPAU55ZUTDl4NLhVSiC3R0UadDxA5rfIHgWIPrGHu7Nt8fHTmBnMWyqQRXlSyCKh1N9khN2G8i8YnK1yazZdF5tbtiuWRr6QkTvnKyAQUbeRWxAsgu9sfslCn2pTjlnCms3IVWdXWHNfHI6Po+IcuD8SF0AAm5NqWzrAkG3A9hNzEg0GtyybRrADxdtCEHLC4JS2JG/08N4nJZqY6s3uT3F5Qw/q1H42X3CZI4cQ/faE5P5nXB95cUPmP8qmCHM4mRWHRplt7NfyUTekE2T703chU2dmxiHN6m8GkaJ2LbDH/tirGmHoNdvCG3iIYGslgm6mlGHDrqrmLUBnoffgFNxdl6bxjTeaAlyB4pywQec1dJy2bZ5gqhPz2tQLfy/5ATZyhQDC9LS6bQ0r43cRHHHdFvGwD7eqRMW3LX9V4Hyzz/lTfestXgTNKX4CkQdJwQ2rQH0=
  template:
    metadata:
      name: esphome-terminal-anthropic-key
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
